// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class ProdFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWbLumIhlOpXAlKWDDsFfQNxjCTpE9RdM',
    appId: '1:286879065430:web:21a00db926460f34ab62f7',
    messagingSenderId: '286879065430',
    projectId: 'gmt-driver-rk',
    authDomain: 'gmt-driver-rk.firebaseapp.com',
    databaseURL: 'https://gmt-driver-rk.firebaseio.com',
    storageBucket: 'gmt-driver-rk.firebasestorage.app',
    measurementId: 'G-9VJMR0FEZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAntZzFhCEN7QdOaL5kmU03nSjex3f-kMU',
    appId: '1:286879065430:android:e71692e2e7ae4e31ab62f7',
    messagingSenderId: '286879065430',
    projectId: 'gmt-driver-rk',
    databaseURL: 'https://gmt-driver-rk.firebaseio.com',
    storageBucket: 'gmt-driver-rk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSgxnbohXG5tHKZ3oujgdshwaawIwt_58',
    appId: '1:286879065430:ios:89ade88bf6fd5a44ab62f7',
    messagingSenderId: '286879065430',
    projectId: 'gmt-driver-rk',
    databaseURL: 'https://gmt-driver-rk.firebaseio.com',
    storageBucket: 'gmt-driver-rk.firebasestorage.app',
    iosBundleId: 'com.skndan.winarch',
  );
}
